import Typography from 'component/Typography'
import React from 'react'
import { Container, ContainerLogo, ImageLogo, ContainerProduct } from './style'
import Logo from '../../assets/images/logo.svg'
function Footer() {
    return (
        <Container>
            <ContainerLogo>
                <ImageLogo src={Logo} alt='logo product' />
            </ContainerLogo>
            <ContainerProduct>
                <Typography
                    variant='Link2'
                    value='Product'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Overview'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Pricing'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Marketplace'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Feature'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='integrations'
                    align='center'
                    mt='24px'
                />
            </ContainerProduct>
            <ContainerProduct>
                <Typography
                    variant='Link2'
                    value='Company'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='about'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Team'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Blog'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Careers'
                    align='center'
                    mt='24px'
                />
            </ContainerProduct>
            <ContainerProduct>
                <Typography
                    variant='Link2'
                    value='Connect'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Contact'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='Newsletter'
                    align='center'
                    mt='24px'
                />
                <Typography
                    variant='Link'
                    value='LinkedIn'
                    align='center'
                    mt='24px'
                    mb='32px'
                />
            </ContainerProduct>
        </Container>
    )
}
export default React.memo(Footer)
